#!/usr/bin/env php
<?php

use peterrehm\gh\Console\Application;

function register_autoloader(array $loaders)
{
    foreach ($loaders as $loader) {
        if (file_exists($loader)) {
            require ($loader);
            return;
        }
    }

    throw new RuntimeException('No autoloader has been found.');
}

register_autoloader([ __DIR__.'/vendor/autoload.php', __DIR__.'/../../autoload.php']);

$application = new Application();
$application->run();
